### ISSUE TITLE
margin before H1, H2, etc.

### ISSUE THREAD

**Issue by yegor256** [yegor256/tacit#69]
Top margin before headers is absent, but should be there.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
0.15.2 96d4c0a 2017-07-30T06:58:34
java.io.IOException: java.lang.IllegalArgumentException: There are 1 parameter(s) but only 0 format argument(s) were provided.
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at com.zerocracy.farm.SmartFarm.lambda$null$4(SmartFarm.java:137)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:89)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:103)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.FlushAction.process(FlushAction.java:85)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:67)
	at com.zerocracy.farm.reactive.FlushAction.exec(FlushAction.java:35)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.func.RunnableOf.run(RunnableOf.java:89)
	at com.jcabi.log.VerboseRunnable.run(VerboseRu...
```
