### ISSUE TITLE
Higher font-weight may increase readability

### ISSUE THREAD

**Issue by davidspinat** [yegor256/tacit#71]
Awesome project! I really love the approach tacit solves styling.

Unfortunately I have a hard times reading paragraphs and regular text with the currently used font-weight. Maybe it's also just my screen, which is not rendering cutting edge High-Res. However I think, font should be accessible and therefore easy to read.

Using font-weight `400` instead of `300` on regular text really bumped up readability for me.

Whats your opinion?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@davidspinat I agree, please submit a pull request. And thanks for using Tacit :)

**Comment by yegor256** [comment]
@rultor release, tag is `1.1.0`

**Comment by yegor256** [comment]
@davidspinat it's fixed and released, see version `1.1.0` Thanks :)

**Comment by davidspinat** [comment]
@yegor256 thank you! Sorry, I was just not fast enough in providing a PR... 😄

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 2212f26 2017-08-18T15:01:07
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:yegor256/tacit#71` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.reactiv...
```
