### ISSUE TITLE
Safari specific issues

### ISSUE THREAD

**Issue by filfreire** [yegor256/tacit#79]
WIP - To be defined.

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:257)
	at com.zerocracy.radars.github.RbByLabel.react(RbByLabel.java:82)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at com.zerocracy.radars.github.RbSafe.react(RbSafe.java:79)
	at com.zerocracy.radars.github.RbLogged.react(RbLogged.java:52)
	at com.zerocracy.radars.github.TkGithub.act(TkGithub.java:161)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:154)
	at...
```

**Comment by filfreire** [comment]
After some investigation, it seems the `page-break-*` rules don't work properly for Safari, in this case affecting the display of labels and inputs.

> Unfortunately page-break-after works differently from browser to browser, one cannot assume a behavior and we thus need to revert to a simpler, known behavior. 
(source: https://stackoverflow.com/a/37604027)

There are a few bugs reported related to Webkit and `page-break-*` rules, example: https://bugs.webkit.org/show_bug.cgi?id=5097

Another way of creating the break after these elements were attempted, following answer https://stackoverflow.com/a/10934138 and it worked for all elements, except input and label elements, the ones affected by the issue.

For input elements, in particular, this workaround reportedly also doesn't work because of the input elements specification, as shown in  https://stackoverflow.com/a/4574946 and https://stackoverflow.com/a/27708091

@yegor256 I think we should close this issue, WDYT?

**Comment by yegor256** [comment]
@filfreire well, the page looks wrong in Safari. We have to find some solution. Can we?

**Comment by 0crat** [comment]
Job [#79](https://github.com/yegor256/tacit/issues/79) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @filfreire[/z](https://www.0crat.com/u/filfreire)

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) everybody who has role `DEV` is banned at [#79](https://github.com/yegor256/tacit/issues/79); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by sanyacastor** [comment]
This may no longer be relevant. Just checked it in Safari 18.6 – everything looks good. If there are any specific steps to reproduce or test on a specific version, please let me know.

<img width="774" height="876" alt="Image" src="https://github.com/user-attachments/assets/dfd42ff5-ebc6-4060-b56b-481348f0703f" />

**Comment by yegor256** [comment]
@filfreire I will close this one. If any similar issues, please submit new tickets.
